### ISSUE TITLE
Merge and Align dataset labels

### ISSUE THREAD

**Issue by zainsarwar865** [mlmed/torchxrayvision#130] opened 2023-03-31 18:05 UTC
Hi.
I am trying to merge multiple datasets (NIH & Padchest) and then trying to train a model on both of them. While I am able to merge, I see that the label ordering was preserved as in the original datasets so basically the same disease in different datasets has a different 1-hot encoding.

Should I manually do the remapping in order to align the 1-hot encodings or is there a function which handles this already?

I could write this function and open a pull request for one if it is currently missing.

Thank you!

**Comment by ieee8023** [comment] 2023-03-31 18:15
It shouldn't let you merge the datasets (if you are using the MergeDataset class) if the pathologies are not aligned: https://github.com/mlmed/torchxrayvision/blob/master/torchxrayvision/datasets.py#L169

Here you can see the MergeDataset class used and the datasets are aligned using the `xrv.datasets.relabel_dataset` function:
```
xrv.datasets.relabel_dataset(list_of_pathologies_you_want, dataset)
```
https://github.com/mlmed/torchxrayvision/blob/master/scripts/xray_datasets.ipynb

**Comment by zainsarwar865** [comment] 2023-04-01 12:55
The pathologies are aligned but their one hot encodings are not. 
My goal is to merge the PadChest and NIH datasets into one containing the mutual pathologies. So what I am doing is I am first relabeling the dataset using the relabel_dataset function using only the mutual pathologies. Then I am merging the datasets using the MergeDataset class. I am able to merge successfully but the one-hot encodings are not aligned. So the disease cardiomegaly has the index 2 in the one-hot encoded label for NIH part of the merged dataset whereas it has the index of 7 in the one-hot label in the PadChest part of the dataset.

**Comment by ieee8023** [comment] 2023-04-01 18:41
Yes exactly. Relabel both datasets to the common set and then the merge will work.

Same thing that is happening here. You may want to use this helper class: https://github.com/mlmed/torchxrayvision/blob/7879060cbe0a8172d8f91ddab786ba707fbfa5ec/scripts/dataset_utils.py#L127-L139

**Comment by ieee8023** [comment] 2023-04-01 18:44
> From my understanding, the relabel_dataset function will make new labels according to how the pathologies_you_want is ordered.

It will create missing labels as columns filled with nan values as well as reorder the columns in .labels to match the specified order.

**Comment by zainsarwar865** [comment] 2023-04-01 20:01
Thank you very much!

**Comment by ieee8023** [comment] 2023-04-12 20:39
> Now the nih_dataset.labels will have the 7 labels but the labels within the dataset (nih_dataset[0]['img']) will still be the original 14.

This shouldn't be the case. nih_dataset[0]['lab'] should only have 7. I just tired it and it appears to work correctly.
![Screen Shot 2023-04-12 at 1 37 10 PM](https://user-images.githubusercontent.com/446367/231578647-9d9e0070-9640-4745-b53d-3288c4401c55.png)

Is it possible that you relabelled the dataset and then have a reference issue to a different dataset object that was not relabelled?

**Closed** 2023-04-12 21:06 UTC

**Comment by ieee8023** [comment] 2023-04-12 21:09
Oh no! I think that is a library problem because it should warn you if you set the labels on a subset or merge dataset. I'll work on adding those warnings. Sorry you had this issue and thanks for making me aware of it so I can fix it!

**Comment by zainsarwar865** [comment] 2023-04-12 21:34
Oh that's great! In case I want to relabel a subset, should I just manually assign them? i.e `nih_dataset_subset[0]['img'] = nih_dataset_subset.labels[0]` for each sample?

Thanks!

**Comment by ieee8023** [comment] 2023-04-12 21:53
It was designed so you would relabel the source dataset object and then take a subset after. Is there any reason why that won't work in your case? You can also create multiple instances of the dataset and relabel them differently.

> nih_dataset_subset[0]['img']

the key is 'lab' not 'img'

**Comment by zainsarwar865** [comment] 2023-04-12 22:06
Got it! I think that should work for my case. It's just that I was trying to only keep samples which have positive labels for the classes I was interested in so I removed the ones which had mutli-labels. But I can just save those indices and take a subset after relabelling.

Thanks a lot for your help!

**Comment by ieee8023** [comment] 2023-04-12 22:21
Ah I see. Yes that should work.
