### ISSUE TITLE
data loading

### ISSUE THREAD

**Issue by danbider** [mlmed/torchxrayvision#11] opened 2020-04-28 22:19 UTC
Hi, 

I use your kaggle dataset object (including all data points) and define a data loader to train my model on a AWS EC2 instance with a GPU. 
I am experiencing a volatile GPU-utility that flickers between 0% and 90%, but mostly at 0%. 
I tried to make my dataloader as efficient
```
    train_loader = torch.utils.data.DataLoader(train_data, 
        batch_size=batch_size, num_workers=8, pin_memory=True, shuffle=True)
```
But I'm also double checking for other places in my code that might slow things down.

I'm curious what was your experience of training using these datasets? did you encounter anything similar?

**Comment by ieee8023** [comment] 2020-04-28 23:22
What transforms are being used? I was training with 32 threads because file IO and data augmentation take some time on my system. Also, you can try to preresize/crop all the images to 224x224 so there is no need to resize them on the fly.

**Comment by danbider** [comment] 2020-04-29 20:20
thanks for the quick response. I found the skimage resize to be the bottleneck https://github.com/mlmed/torchxrayvision/blob/0fc643f3a37f8d9065cb5aba48d4adc3581fea07/torchxrayvision/datasets.py#L1039
it's a couple of orders of magnitude slower than open cv (see print screen)
[resize_time_compare.pdf](https://github.com/mlmed/torchxrayvision/files/4554398/resize_time_compare.pdf)

I locally replaced the resizing function:
```
import cv2
class XRayResizer(object):
    def __init__(self, size):
        self.size = size

    def __call__(self, img):
        '''img: [None, img.shape[0], img.shape[1]] array'''
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            img = img[0,:,:]
            return cv2.resize(img, (self.size, self.size), 
                         interpolation = cv2.INTER_AREA).reshape(
                                1,self.size,self.size).astype(
                                    np.float32)
``` 
which fits to the pipeline as is
```
# define an image transformation for the dataset (in addition to torchxrayvision)
# note, didn't xrv's XRayResizer.
transform = torchvision.transforms.Compose(
    [xrv.datasets.XRayCenterCrop(),
      XRayResizer(args.image_size)]) # typically 224
```
I just sent it off to train now; it initially seems much much faster. let's hope there will be no issues. In addition It was also improved by setting batch_size to 32 and using the 16 workers that I have access to

**Comment by ieee8023** [comment] 2020-04-29 20:27
Makes sense because OpenCV uses native code I believe. So I think it makes sense to include is as an optional resize "engine" that can be used if the caller passes an argument like engine="opencv" to the XRayResizer object. Alternatively it could detect if opencv is installed and if so use that instead transparent to the user. With the second option I am afraid of bugs.

**Comment by danbider** [comment] 2020-04-30 20:40
sounds good. I'm still validating that the resizing is stable and works fine.

**Comment by ieee8023** [comment] 2020-04-30 21:17
I made a pull request here: https://github.com/mlmed/torchxrayvision/pull/12

**Comment by ieee8023** [comment] 2020-05-20 16:05
I tried to add some tests and I found that the resize with cv2 does not match skimage. I tried to add blur (as skimage does) and mess with the anti-alising but I couldn't get a good alignment. I was thinking to just make this the default engine (if cv2 is installed) but I'm afraid this could introducing some issues.

Here is the test code: https://github.com/mlmed/torchxrayvision/blob/test-resize/tests/test_dataloaders.py#L50

**Comment by danbider** [comment] 2020-05-21 14:19
As you said, I guess that the anti-aliasing etc. are the parameters that distinguish these two methods. Why is it a problem that these two will be different? because you want do deploy trained models that were traind on skimage but transform images through cv2?

**Comment by str4w** [comment] 2020-05-23 12:19
OpenCV resize is known to be ....troublesome... from a signal processing perspective.  https://twitter.com/junyanz89/status/1258879217355370497   A library that does it right is ITK, (https://simpleitk.org/) but if you care about the artifacts that are introduced, inevitably you need to increase the order of interpolation which makes it slower.  Since autmentation is being done on the fly, I'd recommend doing the whole resize and augmentation in one step to avoid double resampling, and it should have marginal cost above the augmentation.

**Comment by ieee8023** [comment] 2022-01-31 03:53
Closing this because I think the issue is resolved. Open it again if it is not!

**Closed by ieee8023** 2022-01-31 03:53 UTC
